name: initial

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v
      with:
        python-version: '3.x'

    - name: Install uv
      run: pip install uv==0.5.9

    - name: Run a one-line script
      run: uv run small-test.py

    - uses: actions/upload-artifact@v4
      with:
        path: my-artifact.txt
        name: my-artifact
        retention-days: 1

