name: initial

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
    - name: Run a one-line script
      run: uv run small-test.py