name: initial

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/uv@v4

    - uses: actions/upload-artifact@v4
      with:
        path: my-artifact.txt
        name: my-artifact
        retention-days: 1
    - name: Run a one-line script
      run: uv run small-test.py